version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=rafiulalamkhan
      - PGPASSWORD=postgres
      - PGDATABASE=portfolio
      - PGPORT=5432

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rafiulalamkhan
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

